[kijanikiosk]
api-staging ansible_host="13.60.227.116"
payments-staging ansible_host="13.60.241.146"
logs-staging ansible_host="13.61.177.17"

[kijanikiosk:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/kijanikiosk-key.pem
